### ISSUE TITLE
Create main dashboard

### ISSUE THREAD

**Issue by Daniel-Bindig** [Daniel-Bindig/scribble-space#10]

**Comment by cip170** [comment]
![Image](https://github.com/Daniel-Bindig/scribble-space/assets/134829009/07cdd109-c703-4888-857f-13df8f43596f)

- The idea is that when the respective link button in the menu is clicked, the relevant content will display in the content field (larger square space) and the options to add and remove content, edit the main content and add reminders to the calendar etc, will be linked into the content display rectangle to the left. Both of these content display spaces will display the relative content simultaneously and should automatically save, so that when the button is clicked again, the content has retained the last load of information
